#include "rasterizer.h"
#include "../debugger.h"
#include "../trace.h"

#include <stdlib.h>
#include <string.h>

struct rtdbg_buffer { rt_buffer handle; u08* bytes; usize size; struct rtdbg_buffer* next; };
struct rtdbg_draw { rt_buffer buffer; rt_buffer_range range; usize count; usize first; bool valid; };
struct rtdbg_command_buffer { rt_command_buffer handle; struct rtdbg_draw draw; usize width; usize height; f32 clear[4]; bool rendering; struct rtdbg_command_buffer* next; };
struct rtdbg_program { usize stride, position_offset, color_offset; bool layout_supported; };
struct rtdbg_resource_state { struct rtdbg_buffer* buffers; struct rtdbg_command_buffer* command_buffers; struct rtdbg_program program; };
struct rtdbg_resource_state rtdbg_resource_state;

static struct rtdbg_command_buffer* command_buffer(rt_command_buffer handle) { for (struct rtdbg_command_buffer* record = rtdbg_resource_state.command_buffers; record; record = record->next) if (record->handle == handle) return record; struct rtdbg_command_buffer* record = calloc(1, sizeof(*record)); if (!record) return NULL; record->handle = handle; record->clear[3] = 1; record->next = rtdbg_resource_state.command_buffers; rtdbg_resource_state.command_buffers = record; return record; }
static struct rtdbg_buffer* buffer(rt_buffer handle) { for (struct rtdbg_buffer* record = rtdbg_resource_state.buffers; record; record = record->next) if (record->handle == handle) return record; return NULL; }
static u08 unorm(f32 value) { return value <= 0 ? 0 : value >= 1 ? 255 : (u08)(value * 255 + .5f); }
static f32 edge(f32 ax, f32 ay, f32 bx, f32 by, f32 px, f32 py) { return (px - ax) * (by - ay) - (py - ay) * (bx - ax); }

void rtdbg_rasterizer_reset(void) { while (rtdbg_resource_state.buffers) { struct rtdbg_buffer* record = rtdbg_resource_state.buffers; rtdbg_resource_state.buffers = record->next; free(record->bytes); free(record); } while (rtdbg_resource_state.command_buffers) { struct rtdbg_command_buffer* record = rtdbg_resource_state.command_buffers; rtdbg_resource_state.command_buffers = record->next; free(record); } rtdbg_resource_state.program = (struct rtdbg_program){0}; }
void rtdbg_rasterizer_buffer_data(rt_buffer handle, rt_buffer_range range, const u08* data) { if (!handle || !data || range.offset > SIZE_MAX - range.size) return; struct rtdbg_buffer* record = buffer(handle); if (!record) { record = calloc(1, sizeof(*record)); if (!record) return; record->handle = handle; record->next = rtdbg_resource_state.buffers; rtdbg_resource_state.buffers = record; } usize needed = range.offset + range.size; if (needed > record->size) { u08* bytes = realloc(record->bytes, needed); if (!bytes) return; memset(bytes + record->size, 0, needed - record->size); record->bytes = bytes; record->size = needed; } memcpy(record->bytes + range.offset, data, range.size); }
void rtdbg_rasterizer_layout(const rt_vertex_layout* layout) { rtdbg_resource_state.program.layout_supported = false; if (!layout || layout->input_count != 1 || !layout->inputs || layout->inputs[0].attribute_count < 2) return; const rt_vertex_input* input = &layout->inputs[0]; const rt_vertex_attribute* attributes = input->attributes; if (attributes[0].format != RT_RG32_SFLOAT || attributes[1].format != RT_RGB32_SFLOAT) return; rtdbg_resource_state.program.stride = input->stride; rtdbg_resource_state.program.position_offset = attributes[0].offset; rtdbg_resource_state.program.color_offset = attributes[1].offset; rtdbg_resource_state.program.layout_supported = input->stride >= attributes[1].offset + 3 * sizeof(f32); }
void rtdbg_rasterizer_vertex_buffer(rt_command_buffer handle, rt_buffer source, rt_buffer_range range) { struct rtdbg_command_buffer* record = command_buffer(handle); if (record) record->draw = (struct rtdbg_draw){source, range, 0, 0, rtdbg_resource_state.program.layout_supported}; }
void rtdbg_rasterizer_draw(rt_command_buffer handle, usize count, usize first) { struct rtdbg_command_buffer* record = command_buffer(handle); if (record) { record->draw.count = count; record->draw.first = first; } }
void rtdbg_rasterizer_begin(rt_command_buffer handle) { struct rtdbg_command_buffer* record = command_buffer(handle); if (record) record->rendering = true; }
void rtdbg_rasterizer_clear_color(rt_command_buffer handle, f32 r, f32 g, f32 b, f32 a) { struct rtdbg_command_buffer* record = command_buffer(handle); if (record) { record->clear[0]=r;record->clear[1]=g;record->clear[2]=b;record->clear[3]=a; } }
void rtdbg_rasterizer_viewport(rt_command_buffer handle, usize width, usize height) { struct rtdbg_command_buffer* record = command_buffer(handle); if (record) { record->width=width;record->height=height; } }
void rtdbg_rasterizer_execute(rt_command_buffer primary, rt_command_buffer secondary) { struct rtdbg_command_buffer* p = command_buffer(primary); struct rtdbg_command_buffer* s = command_buffer(secondary); if (!p || !s || !p->rendering || !p->width || !p->height || !s->draw.valid || s->draw.count < 3 || p->width > 4096 || p->height > 4096) return; struct rtdbg_buffer* source = buffer(s->draw.buffer); if (!source || s->draw.range.offset > source->size) return; usize base = s->draw.range.offset + s->draw.first * rtdbg_resource_state.program.stride; if (base > source->size || s->draw.count > (source->size - base) / rtdbg_resource_state.program.stride) return; usize pixels_size = p->width * p->height * 4; u08* pixels = malloc(pixels_size); if (!pixels) return; for (usize i=0;i<p->width*p->height;++i) { pixels[i*4]=unorm(p->clear[0]);pixels[i*4+1]=unorm(p->clear[1]);pixels[i*4+2]=unorm(p->clear[2]);pixels[i*4+3]=unorm(p->clear[3]); } for (usize triangle=0;triangle+2<s->draw.count;triangle+=3) { const u08* v[3]={source->bytes+base+(triangle+0)*rtdbg_resource_state.program.stride,source->bytes+base+(triangle+1)*rtdbg_resource_state.program.stride,source->bytes+base+(triangle+2)*rtdbg_resource_state.program.stride}; f32 x[3],y[3],color[3][3]; for(unsigned i=0;i<3;++i){memcpy(&x[i],v[i]+rtdbg_resource_state.program.position_offset,4);memcpy(&y[i],v[i]+rtdbg_resource_state.program.position_offset+4,4);memcpy(color[i],v[i]+rtdbg_resource_state.program.color_offset,12);x[i]=(x[i]*.5f+.5f)*(f32)(p->width-1);y[i]=(1-(y[i]*.5f+.5f))*(f32)(p->height-1);} f32 area=edge(x[0],y[0],x[1],y[1],x[2],y[2]); if(area==0)continue; for(usize py=0;py<p->height;++py)for(usize px=0;px<p->width;++px){f32 w0=edge(x[1],y[1],x[2],y[2],(f32)px+.5f,(f32)py+.5f)/area,w1=edge(x[2],y[2],x[0],y[0],(f32)px+.5f,(f32)py+.5f)/area,w2=1-w0-w1;if(w0<0||w1<0||w2<0)continue;u08* out=pixels+(py*p->width+px)*4;for(unsigned channel=0;channel<3;++channel)out[channel]=unorm(w0*color[0][channel]+w1*color[1][channel]+w2*color[2][channel]);out[3]=255;} } rtdbg_debugger_texture_preview(0xffffffffffffffffull,p->width,p->height,pixels,pixels_size); free(pixels); rtdbg_trace_event(RTDBG_TRACE_COMMAND, "rt-debug software rasterizer rendered %llu x %llu", (unsigned long long)p->width, (unsigned long long)p->height); }
