#ifndef RTDBG_INTERNAL_RT_GLFW_SWAPCHAIN_H
#define RTDBG_INTERNAL_RT_GLFW_SWAPCHAIN_H

#include "rt_swapchain.h"

#define RT_GLFW_SWAPCHAIN_VERSION RT_HEADER_VERSION

#endif /* RTDBG_INTERNAL_RT_GLFW_SWAPCHAIN_H */

